


spring.application.name=StudentProgressTracker

app.seed-demo-data=false

server.port=8080

spring.data.mongodb.uri=mongodb+srv://omphopse96_db_user:d3I54h6goxlY9hct@cluster0.7gflybj.mongodb.net/student?retryWrites=true&w=majority
spring.data.mongodb.database=student


logging.level.org.springframework=INFO
logging.level.com.example=DEBUG


# JWT Configuration
jwt.secret=MySecretKeyForStudentProgressTrackerProject123456789
jwt.expiration=86400000
#24 Hours=86400000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=omphopse96@gmail.com
spring.mail.password=pwae vmcy glbu roaq

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true