spring.application.name=StudentProgressTracker
app.seed-demo-data=false
server.port=8080

spring.data.mongodb.uri=mongodb://localhost:27017/student
spring.data.mongodb.database=student

logging.level.org.springframework=INFO
logging.level.com.example=DEBUG

# JWT Configuration
jwt.secret=${JWT_SECRET:MySecretKeyForStudentProgressTrackerProject123456789}
jwt.expiration=86400000

# Mail Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:omphopse96@gmail.com}
spring.mail.password=${MAIL_PASSWORD:pwae vmcy glbu roaq}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true