spring.application.name=SPT


spring.application.name=StudentProgressTracker

server.port=8080

spring.data.mongodb.uri=mongodb://localhost:27017/student_progress_tracker


logging.level.org.springframework=INFO
logging.level.com.example=DEBUG


# JWT Configuration
jwt.secret=MySecretKeyForStudentProgressTrackerProject123456789
jwt.expiration=86400000
#24 Hours=86400000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=omchanne2024@gmail.com
spring.mail.password=saej hseg jwrv fyyf

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true