package com.example.SPT.enums;

public enum ApplicationStatus {

    SUBMITTED,
    UNDER_REVIEW,

    APTITUDE_SCHEDULED,
    APTITUDE_PASSED,
    APTITUDE_FAILED,

    TECHNICAL_INTERVIEW_SCHEDULED,
    TECHNICAL_INTERVIEW_PASSED,
    TECHNICAL_INTERVIEW_FAILED,

    HR_INTERVIEW_SCHEDULED,
    HR_INTERVIEW_PASSED,
    HR_INTERVIEW_FAILED,

    DOCUMENT_VERIFICATION_PENDING,
    DOCUMENT_VERIFIED,
    DOCUMENT_REJECTED,

    HOME_VISIT_SCHEDULED,
    HOME_VISIT_COMPLETED,

    SELECTED,
    REJECTED,
    WAITLISTED
}